# Generated by Django 2.2.7 on 2019-12-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workplace',
            unique_together={('job', 'employee')},
        ),
    ]
