# Generated by Django 2.2.7 on 2019-12-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_statistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktime',
            options={'ordering': ['-date']},
        ),
    ]
